# Generated by Django 5.2.4 on 2025-08-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='created_by',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
